// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InfoService.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace InfoServiceGRPC {
  public static partial class InfoGRPC
  {
    static readonly string __ServiceName = "InfoGRPC";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::InfoServiceGRPC.AddPassengerRequest> __Marshaller_AddPassengerRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::InfoServiceGRPC.AddPassengerRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::InfoServiceGRPC.AddUserResponse> __Marshaller_AddUserResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::InfoServiceGRPC.AddUserResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::InfoServiceGRPC.AddDriverRequest> __Marshaller_AddDriverRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::InfoServiceGRPC.AddDriverRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::InfoServiceGRPC.AddStaffRequest> __Marshaller_AddStaffRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::InfoServiceGRPC.AddStaffRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::InfoServiceGRPC.AddPassengerRequest, global::InfoServiceGRPC.AddUserResponse> __Method_AddPassenger = new grpc::Method<global::InfoServiceGRPC.AddPassengerRequest, global::InfoServiceGRPC.AddUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddPassenger",
        __Marshaller_AddPassengerRequest,
        __Marshaller_AddUserResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::InfoServiceGRPC.AddDriverRequest, global::InfoServiceGRPC.AddUserResponse> __Method_AddDriver = new grpc::Method<global::InfoServiceGRPC.AddDriverRequest, global::InfoServiceGRPC.AddUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddDriver",
        __Marshaller_AddDriverRequest,
        __Marshaller_AddUserResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::InfoServiceGRPC.AddStaffRequest, global::InfoServiceGRPC.AddUserResponse> __Method_AddStaff = new grpc::Method<global::InfoServiceGRPC.AddStaffRequest, global::InfoServiceGRPC.AddUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddStaff",
        __Marshaller_AddStaffRequest,
        __Marshaller_AddUserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::InfoServiceGRPC.InfoServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InfoGRPC</summary>
    [grpc::BindServiceMethod(typeof(InfoGRPC), "BindService")]
    public abstract partial class InfoGRPCBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::InfoServiceGRPC.AddUserResponse> AddPassenger(global::InfoServiceGRPC.AddPassengerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::InfoServiceGRPC.AddUserResponse> AddDriver(global::InfoServiceGRPC.AddDriverRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::InfoServiceGRPC.AddUserResponse> AddStaff(global::InfoServiceGRPC.AddStaffRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InfoGRPC</summary>
    public partial class InfoGRPCClient : grpc::ClientBase<InfoGRPCClient>
    {
      /// <summary>Creates a new client for InfoGRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public InfoGRPCClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InfoGRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public InfoGRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected InfoGRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected InfoGRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddPassenger(global::InfoServiceGRPC.AddPassengerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPassenger(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddPassenger(global::InfoServiceGRPC.AddPassengerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddPassenger, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddPassengerAsync(global::InfoServiceGRPC.AddPassengerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPassengerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddPassengerAsync(global::InfoServiceGRPC.AddPassengerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddPassenger, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddDriver(global::InfoServiceGRPC.AddDriverRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddDriver(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddDriver(global::InfoServiceGRPC.AddDriverRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddDriver, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddDriverAsync(global::InfoServiceGRPC.AddDriverRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddDriverAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddDriverAsync(global::InfoServiceGRPC.AddDriverRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddDriver, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddStaff(global::InfoServiceGRPC.AddStaffRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddStaff(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::InfoServiceGRPC.AddUserResponse AddStaff(global::InfoServiceGRPC.AddStaffRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddStaff, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddStaffAsync(global::InfoServiceGRPC.AddStaffRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddStaffAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::InfoServiceGRPC.AddUserResponse> AddStaffAsync(global::InfoServiceGRPC.AddStaffRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddStaff, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override InfoGRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InfoGRPCClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(InfoGRPCBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddPassenger, serviceImpl.AddPassenger)
          .AddMethod(__Method_AddDriver, serviceImpl.AddDriver)
          .AddMethod(__Method_AddStaff, serviceImpl.AddStaff).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, InfoGRPCBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddPassenger, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::InfoServiceGRPC.AddPassengerRequest, global::InfoServiceGRPC.AddUserResponse>(serviceImpl.AddPassenger));
      serviceBinder.AddMethod(__Method_AddDriver, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::InfoServiceGRPC.AddDriverRequest, global::InfoServiceGRPC.AddUserResponse>(serviceImpl.AddDriver));
      serviceBinder.AddMethod(__Method_AddStaff, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::InfoServiceGRPC.AddStaffRequest, global::InfoServiceGRPC.AddUserResponse>(serviceImpl.AddStaff));
    }

  }
}
#endregion
